swagger: "2.0"
info:
  description: "This is a tiny emulation of the spotify service."
  version: "1.0.0"
  title: "Spotify-Service"
  contact:
    email: "germansanz93@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
tags:
- name: "Album"
  description: "Album operations"
- name: "Artist"
  description: "Artist Operations"

schemes:
- "https"
- "http"
paths:
  /album:
    get:
      tags:
      - "Album"
      summary: "Returns all albums"
      operationId: "getAlbums"
      produces:
      - "application/json"
      responses: 
        200:
          description: "Ok"
          schema: 
            $ref: "#/definitions/ArrayOfAlbums"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/ErrorBadRequestResponse"
        404:
          description: "Not Found"
          schema:
            $ref: "#/definitions/ErrorNotFoundResponse"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/ErrorInternalServerResponse"
    post:
      tags:
      - "Album"
      summary: "Create an album"
      operationId: "CreateAlbum"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "album"
        description: "Album that needs to be added to the app"
        required: true
        schema:
          $ref: "#/definitions/AlbumInput"
      responses:
        201:
          description: "CREATED"
          schema:
            $ref: "#/definitions/AlbumResponse"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/ErrorBadRequestResponse"
        404:
          description: "Not Found"
          schema:
            $ref: "#/definitions/ErrorNotFoundResponse"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/ErrorInternalServerResponse"
  /album/{idAlbum}:
    get:
      tags:
      - "Album"
      summary: "Get an album by id"
      operationId: "GetAlbumById"
      produces:
        - "application/json"
      parameters:
      - name: "idAlbum"
        in: "path"
        description: "id of album to return"
        required: true
        type: "number"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/AlbumResponse"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/ErrorBadRequestResponse"
        404:
          description: "Not Found"
          schema:
            $ref: "#/definitions/ErrorNotFoundResponse"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/ErrorInternalServerResponse"
    put:
      tags:
      - "Album"
      summary: "Update an Album"
      operationId: "UpdateAlbum"
      produces:
      - "application/json"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "album"
        description: "Album that needs to be added to the app"
        required: true
        schema:
          $ref: "#/definitions/AlbumInput"
      responses:
        200:
          description: "Album updated"
          schema:
            $ref: "#/definitions/AlbumResponse"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/ErrorBadRequestResponse"
        404:
          description: "Not Found"
          schema:
            $ref: "#/definitions/ErrorNotFoundResponse"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/ErrorInternalServerResponse"
    delete:
      tags:
      - "Album"
      summary: "Delete an album"
      operationId: "DeleteAlbum"
      produces:
      - "application/json"
      parameters:
      - name: "idAlbum"
        in: "path"
        description: "id of the album to delete"
        required: true
        type: "number"
      responses:
        200:
          description: "Album deleted"

        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/ErrorBadRequestResponse"
        404:
          description: "Not Found"
          schema:
            $ref: "#/definitions/ErrorNotFoundResponse"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/ErrorInternalServerResponse"
  /artist:
    get:
      tags:
      - "Artist"
      summary: "Returns all artists"
      operationId: "getArtists"
      produces:
      - "application/json"
      responses: 
        200:
          description: "Ok"
          schema: 
            $ref: "#/definitions/ArrayOfArtists"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/ErrorBadRequestResponse"
        404:
          description: "Not Found"
          schema:
            $ref: "#/definitions/ErrorNotFoundResponse"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/ErrorInternalServerResponse"
    post:
      tags:
      - "Artist"
      summary: "Create an artist"
      operationId: "CreateArtist"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Artist that needs to be added to the app"
        required: true
        schema:
          $ref: "#/definitions/ArtistInput"
      responses:
        201:
          description: "CREATED"
          schema:
            $ref: "#/definitions/ArtistResponse"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/ErrorBadRequestResponse"
        404:
          description: "Not Found"
          schema:
            $ref: "#/definitions/ErrorNotFoundResponse"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/ErrorInternalServerResponse"
  /artist/{idArtist}:
    get:
      tags:
      - "Artist"
      summary: "Get artist by id"
      operationId: "getArtist"
      parameters:
      - name: "idArtist"
        in: "path"
        description: "id of a to return"
        required: true
        type: "number"
      produces:
      - "application/json"
      responses: 
        200:
          description: "Ok"
          schema: 
            $ref: "#/definitions/ArtistResponse"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/ErrorBadRequestResponse"
        404:
          description: "Not Found"
          schema:
            $ref: "#/definitions/ErrorNotFoundResponse"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/ErrorInternalServerResponse"
    put:
      tags:
      - "Artist"
      summary: "Update an Artist"
      operationId: "UpdateArtist"
      produces:
      - "application/json"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "idArtist"
        description: "Artist that needs to be added to the app"
        required: true
        schema:
          $ref: "#/definitions/ArtistInput"
      responses:
        200:
          description: "Artist updated"
          schema:
            $ref: "#/definitions/ArtistResponse"
        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/ErrorBadRequestResponse"
        404:
          description: "Not Found"
          schema:
            $ref: "#/definitions/ErrorNotFoundResponse"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/ErrorInternalServerResponse"
    delete:
      tags:
      - "Artist"
      summary: "Delete an artist"
      operationId: "DeleteArtist"
      produces:
      - "application/json"
      parameters:
      - name: "idArtist"
        in: "path"
        description: "id of the artist to delete"
        required: true
        type: "number"
      responses:
        200:
          description: "Artist deleted"

        400:
          description: "Bad Request"
          schema:
            $ref: "#/definitions/ErrorBadRequestResponse"
        404:
          description: "Not Found"
          schema:
            $ref: "#/definitions/ErrorNotFoundResponse"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/ErrorInternalServerResponse" 
    

definitions:
  ArrayOfAlbums:
    type: "array"
    items:
      properties:
        idAlbum:
          type: "number"
        artist:
          type: "object"
          properties: 
            schema:
              $ref: "#/definitions/ArtistResponse"
        name:
          type: "string"
  
  ArrayOfArtists:
    type: "array"
    items:
      properties:
        idArtist:
          type: "number"
        name:
          type: "string"
        genre:
          type: "string"
        image:
          type: "string"
          
  AlbumInput:
    type: "object"
    properties:
      idArtist:
        type: "number"
      name:
        type: "string"
        
  ArtistInput:
    type: "object"
    properties: 
      name:
        type: "string"
      genre:
        type: "string"
      image:
        type: "string"
        
  AlbumResponse:
    type: "object"
    properties:
      idAlbum:
        type: "number"
      idArtist:
        type: "number"
      name:
        type: "string"
  
  ArtistResponse:
    type: "object"
    properties:
      idArtist:
        type: "number"
      name:
        type: "string"
      genre:
        type: "string"
      image:
        type: "string"
  
  ErrorNotFoundResponse:
    type: "object"
    properties:
      code:
        type: "string"
        example: "GENERIC_NOT_FOUND"
      message:
        type: "string"
        example: "Resource Not Found"
      result:
        type: "string"
        example: "GENERIC_NOT_FOUND"
  
  ErrorBadRequestResponse:
    type: "object"
    properties:
      code:
        type: "string"
        example: "GENERIC_BAD_REQUEST"
      message:
        type: "string"
        example: "Invalid Request"
      result:
        type: "string"
        example: "GENERIC_NOT_FOUND"
  
  ErrorInternalServerResponse:
    type: "object"
    properties:
      code:
        type: "string"
        example: "GENERIC_INTERNAL_SERVER_ERROR"
      message:
        type: "string"
        example: "Internal Server Error"
      result:
        type: "string"
        example: "GENERIC_INTERNAL_SERVER_ERROR"